// send fax
const config = require('config')
const sip = require ('sip-lab')
const Zeq = require('@mayama/zeq')
const m = require('data-matching')
const sip_msg = require('sip-matching')
const path = require('path')

// create our Zeq instance
var z = new Zeq()
let oc

async function test() {
    // set trap for events generated by sip-lab
    z.trap_events(sip.event_source, 'event', (evt) => {
        var e = evt.args[0]
        return e
    })

    // set list of available codecs (just to make SIP messages to be shorter)
    sip.set_codecs("pcmu/8000/1:128,pcma/8000/1:128,gsm/8000/1:128")

    // set the timeout in milliseconds to notify aggregatedd DTMF digits
    // sip.dtmf_aggregation_on(500)

    // start sip-lab
    console.log(sip.start((data) => { console.log(data)} ))

    // create a transport
    const t1 = sip.transport.create({address: config.local_ip})

    let calling_number = '0312341234'
    let called_number = '05033334444'

    // print t1 
    console.log("t1", t1)

    // create a call to freeswitch public interface (port 5080)
    oc = sip.call.create(t1.id, {
        from_uri: `sip:${calling_number}@test.com`,
        to_uri: `sip:${called_number}@${config.local_ip}:5080`,
    })

    // wait for replies from freeswitch
    await z.wait([
        {
            event: 'response',
            call_id: oc.id,
            method: 'INVITE',
            msg: sip_msg({
                $rs: '100',
                $rr: 'Trying',
            }),
        },
        {
            event: 'response',
            call_id: oc.id,
            method: 'INVITE',
            msg: sip_msg({
                $rs: '200',
                $rr: 'OK',
            }),
        },
        {
            event: 'media_update',
            call_id: oc.id,
            status: 'ok',
        },
    ], 1000)

    // wait a little for the voice path to be established.
    await z.sleep(500)

    const in_file = path.resolve(__dirname, '../artifacts/sample.tiff')

    // start to send fax
    sip.call.start_fax(oc.id, {
        is_sender: true,
        file: in_file,
        transmit_on_idle: true,
    })

    // wait for transfer the image
    await z.wait([
        {
            event: 'fax_result',
            call_id: oc.id,
            result: 0,
        },
    ], 60 * 1000)

    // wait a little for the fax communication to be finished.
    await z.sleep(500)

    // wait for termination events
    await z.wait([
        {
            event: 'call_ended',
            call_id: oc.id,
        },
    ], 5000)

    console.log("Success")

    sip.stop()
    process.exit(0)
}


test()
.catch(e => {
    console.error(e)
    sip.call.terminate(oc.id)
    process.exit(1)
})


